spring:
  application:
    name: votacao-api

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  level:
    com.cesar: DEBUG

  h2:
    console:
      enabled: true
      path: /h2-console